
name: Build common images and upload to use it across jobs

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./docker/${{inputs.image}}/Dockerfile
            tags: ${{inputs.image}}
            outputs: type=docker,dest=/tmp/${{inputs.image}}.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.image}}
          path: /tmp/${{inputs.image}}.tar
