name: insights-app workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  call-workflow-build-common-images:
    runs-on: ubuntu-latest
    steps:
      - name: Call Build Common Images Workflow
        uses: ./.github/workflows/common-images-build.yml@master
        with:
          image: libs

  call-workflow-push-ecr:
    needs: call-workflow-build-common-images
    runs-on: ubuntu-latest
    steps:
      - name: Call Push to ECR Workflow
        uses: ./.github/workflows/common-push-ecr.yml@master
        with:
          repository: insights-app
          imageTag: ${{ github.sha }}
          commonImageName: libs
