name: insights-app workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  call-workflow-build-common-images:
    if: ${{ github.event_name == 'pull_request' || github.base_ref == 'master' }}
    uses: ./.github/workflows/common-images-build.yml
    with:
      image: libs
    secrets: inherit

  call-workflow-push-ecr:
    needs:  
      [
        call-workflow-build-common-images
      ]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/common-push-ecr.yml
    secrets: inherit
    with:
      commonImageName: libs
      repository: insights-app
      dockerFolder: ./docker/insights-app/
      imageTag: ${{ github.sha }}

  call-workflow-deploy-ecs-task:
    needs:  
      [  call-workflow-build-common-images, call-workflow-push-ecr ]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/common-deploy-env.yml
    with:
      service-name:  prod-insight-insights-app-service
      task-definition: prod-insight-insights-app
      image-name: insights-app-testnet
      dockerFolder: ./
      container-name: prod-insight-insights-app-task
      environment: dev
      tag: ${{ github.sha }}
    secrets: inherit
